// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	entity "BE_Manage_device/internal/domain/entity"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"
)

// AssetsLogRepository is an autogenerated mock type for the AssetsLogRepository type
type AssetsLogRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: assetsLog, tx
func (_m *AssetsLogRepository) Create(assetsLog *entity.AssetLog, tx *gorm.DB) (*entity.AssetLog, error) {
	ret := _m.Called(assetsLog, tx)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.AssetLog
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.AssetLog, *gorm.DB) (*entity.AssetLog, error)); ok {
		return rf(assetsLog, tx)
	}
	if rf, ok := ret.Get(0).(func(*entity.AssetLog, *gorm.DB) *entity.AssetLog); ok {
		r0 = rf(assetsLog, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.AssetLog)
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.AssetLog, *gorm.DB) error); ok {
		r1 = rf(assetsLog, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDB provides a mock function with no fields
func (_m *AssetsLogRepository) GetDB() *gorm.DB {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDB")
	}

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

// GetLogByAssetId provides a mock function with given fields: assetId
func (_m *AssetsLogRepository) GetLogByAssetId(assetId int64) ([]*entity.AssetLog, error) {
	ret := _m.Called(assetId)

	if len(ret) == 0 {
		panic("no return value specified for GetLogByAssetId")
	}

	var r0 []*entity.AssetLog
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) ([]*entity.AssetLog, error)); ok {
		return rf(assetId)
	}
	if rf, ok := ret.Get(0).(func(int64) []*entity.AssetLog); ok {
		r0 = rf(assetId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.AssetLog)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(assetId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNewLogByAssetId provides a mock function with given fields: assetId
func (_m *AssetsLogRepository) GetNewLogByAssetId(assetId int64) (*entity.AssetLog, error) {
	ret := _m.Called(assetId)

	if len(ret) == 0 {
		panic("no return value specified for GetNewLogByAssetId")
	}

	var r0 *entity.AssetLog
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (*entity.AssetLog, error)); ok {
		return rf(assetId)
	}
	if rf, ok := ret.Get(0).(func(int64) *entity.AssetLog); ok {
		r0 = rf(assetId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.AssetLog)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(assetId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAssetsLogRepository creates a new instance of AssetsLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAssetsLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AssetsLogRepository {
	mock := &AssetsLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
