export { default as AllAssets } from './all-assets'
export { default as CreateAsset } from './create-assets'
export { default as AssetDetail } from './asset-detail'
export { default as UpdateAsset } from './update-asset'
export { default as ViewAllMaintenanceSchedule } from './view-all-maintenance-schedule'
