// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	entity "BE_Manage_device/internal/domain/entity"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"
)

// UserRBACRepository is an autogenerated mock type for the UserRBACRepository type
type UserRBACRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: userRBAC, tx
func (_m *UserRBACRepository) Create(userRBAC *entity.UserRbac, tx *gorm.DB) error {
	ret := _m.Called(userRBAC, tx)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.UserRbac, *gorm.DB) error); ok {
		r0 = rf(userRBAC, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserRBACRepository creates a new instance of UserRBACRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRBACRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRBACRepository {
	mock := &UserRBACRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
