export { default as AssetsPage } from './assets-page'
export { default as CreateAssetPage } from './create-asset-page'
export { default as AssetDetailPage } from './asset-detail-page'
export { default as UpdateAssetPage } from './update-asset-page'
export { default as ViewAllMaintenanceSchedulePage } from './view-all-maintenance-schedule-page'
export { default as CreateAssetMaintenanceSchedulePage } from './create-asset-maintenance-schedule-page'
export { default as AssetComparisonPage } from './asset-comparison-page'
