export { default as LoginPage } from './login-page'
export { default as SignupPage } from './signup-page'
export { default as DashboardPage } from './dashboard-page'
export { default as ForgetPasswordPage } from './forget-password-page'
export { default as ResetPasswordPage } from './reset-password-page'
